### ISSUE TITLE
Добавить модульное тестирование.

### ISSUE THREAD

**Issue by V-Makarov** [is541-sibsutis/train-schedule#13]
Для корректной работы программы и максимального снижения случаев "падения" нужно сделать модульное тестирование.

**Comment by groneveld** [comment]
Тестирование функционала программы на разных этапах
+<groneveld>

**Comment by groneveld** [comment]
Проблемы с мейкфайлом для тестирования @V-Makarov

**Comment by groneveld** [comment]
Напоминаю, что мейкфайл заменен для удобства тестирования. 
@V-Makarov

**Comment by groneveld** [comment]
Модульное тестирование выполнено на 5 функциях программы.
Успешно выполнено 15 тестов.
